- name: Common task for bootstrap
  block:
    - name: Install bootstrap dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gpg
        - amazon-ec2-utils
      tags:
        - bootstrap
        - dependencies

    - name: Make sure that any conflicting packages are uninstalled
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      loop:
        - containerd
        - docker.io
        - docker-doc
        - docker-compose
        - podman-docker
        - runc
      tags:
        - bootstrap
        - dependencies
        - conflict

    - name: Create the /etc/apt/keyrings directory if it does not exist
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      tags:
        - bootstrap
        - debian
        - ubuntu
      when:
        (ansible_distribution == "Debian" and ansible_distribution_major_version|int < 12) or
        (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 22)


- name: Configure and Install docker, containerd and friends from upstream (docker.com)
  block:
    - name: Register dpkg architecture
      ansible.builtin.command:
        cmd: dpkg --print-architecture
      register: dpkg_architecture
      changed_when: false
      tags:
        - bootstrap
        - containerd

    - name: Download and install gpg key
      ansible.builtin.shell:
        cmd: |
          curl -fsSL https://download.docker.com/linux/debian/gpg |\
          gpg --dearmor --output /etc/apt/keyrings/docker.gpg
        creates: /etc/apt/keyrings/docker.gpg
      tags:
        - bootstrap
        - containerd

    - name: Add docker apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present
        filename: docker
      tags:
        - bootstrap
        - containerd

    - name: Install recommended packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        default_release: "{{ ansible_distribution_release }}"
      loop:
        - containerd.io
        - docker-ce
        - docker-ce-cli
        - docker-buildx-plugin
        - docker-compose-plugin
        - python3-docker
      tags:
        - bootstrap
        - containerd
