# The idea of this configuration file is to be a single source of truth for the bootstrap script, ansible and terraform.
project_name: Yunga
aws_region: eu-central-1
keypair_name: yunga
vault_path: vault
data_device_name: /dev/sdf

git:
  username: coati
  token_filename: deploy_token
  repository_url: gitlab.com/jungle.ai/yungas.git

# to be prefixed with the account_id and region ex: 123456789012-eu-central-1-terraform-backend-yunga
terraform:
  backend_bucket: terraform-backend-yunga