global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# scrape configuration
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: "node-exporter-backend"
    scrape_interval: 5s
    static_configs:
      - targets: ["127.0.0.1:9100"]

# TODO: create a simple python script to retrieve the IP for the frontend VM using tags.
#  - job_name: "node-exporter-frontend"
#    scrape_interval: 5s
#    static_configs:
#      - targets: ["xx.xx.xx.xx:9100"]
